server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lease
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      pool-name: SPHHikariPool

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
